In [1]:
import torch

In [10]:
a = torch.arange(2*3*4*5).reshape(2,3,4,5)

In [11]:
a

tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])

In [12]:
b = torch.arange(1000, 1000 + 2*3*4*5).reshape(2,3,4,5)

In [13]:
b

tensor([[[[1000, 1001, 1002, 1003, 1004],
          [1005, 1006, 1007, 1008, 1009],
          [1010, 1011, 1012, 1013, 1014],
          [1015, 1016, 1017, 1018, 1019]],

         [[1020, 1021, 1022, 1023, 1024],
          [1025, 1026, 1027, 1028, 1029],
          [1030, 1031, 1032, 1033, 1034],
          [1035, 1036, 1037, 1038, 1039]],

         [[1040, 1041, 1042, 1043, 1044],
          [1045, 1046, 1047, 1048, 1049],
          [1050, 1051, 1052, 1053, 1054],
          [1055, 1056, 1057, 1058, 1059]]],


        [[[1060, 1061, 1062, 1063, 1064],
          [1065, 1066, 1067, 1068, 1069],
          [1070, 1071, 1072, 1073, 1074],
          [1075, 1076, 1077, 1078, 1079]],

         [[1080, 1081, 1082, 1083, 1084],
          [1085, 1086, 1087, 1088, 1089],
          [1090, 1091, 1092, 1093, 1094],
          [1095, 1096, 1097, 1098, 1099]],

         [[1100, 1101, 1102, 1103, 1104],
          [1105, 1106, 1107, 1108, 1109],
          [1110, 1111, 1112, 1113, 1114],
          [1115, 1116,

In [14]:
a * b

tensor([[[[     0,   1001,   2004,   3009,   4016],
          [  5025,   6036,   7049,   8064,   9081],
          [ 10100,  11121,  12144,  13169,  14196],
          [ 15225,  16256,  17289,  18324,  19361]],

         [[ 20400,  21441,  22484,  23529,  24576],
          [ 25625,  26676,  27729,  28784,  29841],
          [ 30900,  31961,  33024,  34089,  35156],
          [ 36225,  37296,  38369,  39444,  40521]],

         [[ 41600,  42681,  43764,  44849,  45936],
          [ 47025,  48116,  49209,  50304,  51401],
          [ 52500,  53601,  54704,  55809,  56916],
          [ 58025,  59136,  60249,  61364,  62481]]],


        [[[ 63600,  64721,  65844,  66969,  68096],
          [ 69225,  70356,  71489,  72624,  73761],
          [ 74900,  76041,  77184,  78329,  79476],
          [ 80625,  81776,  82929,  84084,  85241]],

         [[ 86400,  87561,  88724,  89889,  91056],
          [ 92225,  93396,  94569,  95744,  96921],
          [ 98100,  99281, 100464, 101649, 102836],
  

In [18]:
r= a.unsqueeze(-1) * b.unsqueeze(-2)

In [19]:
r.shape

torch.Size([2, 3, 4, 5, 5])

In [20]:
r

tensor([[[[[     0,      0,      0,      0,      0],
           [  1000,   1001,   1002,   1003,   1004],
           [  2000,   2002,   2004,   2006,   2008],
           [  3000,   3003,   3006,   3009,   3012],
           [  4000,   4004,   4008,   4012,   4016]],

          [[  5025,   5030,   5035,   5040,   5045],
           [  6030,   6036,   6042,   6048,   6054],
           [  7035,   7042,   7049,   7056,   7063],
           [  8040,   8048,   8056,   8064,   8072],
           [  9045,   9054,   9063,   9072,   9081]],

          [[ 10100,  10110,  10120,  10130,  10140],
           [ 11110,  11121,  11132,  11143,  11154],
           [ 12120,  12132,  12144,  12156,  12168],
           [ 13130,  13143,  13156,  13169,  13182],
           [ 14140,  14154,  14168,  14182,  14196]],

          [[ 15225,  15240,  15255,  15270,  15285],
           [ 16240,  16256,  16272,  16288,  16304],
           [ 17255,  17272,  17289,  17306,  17323],
           [ 18270,  18288,  18306,  183

In [22]:
torch.arange(5).unsqueeze(-1)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [23]:
torch.arange(10, 10 + 5).unsqueeze(-2)

tensor([[10, 11, 12, 13, 14]])

In [24]:
torch.arange(5).unsqueeze(-1) * torch.arange(10, 10 + 5).unsqueeze(-2)

tensor([[ 0,  0,  0,  0,  0],
        [10, 11, 12, 13, 14],
        [20, 22, 24, 26, 28],
        [30, 33, 36, 39, 42],
        [40, 44, 48, 52, 56]])

In [25]:
torch.arange(5).unsqueeze(-1) @ torch.arange(10, 10 + 5).unsqueeze(-2)

tensor([[ 0,  0,  0,  0,  0],
        [10, 11, 12, 13, 14],
        [20, 22, 24, 26, 28],
        [30, 33, 36, 39, 42],
        [40, 44, 48, 52, 56]])

In [40]:
torch.asarray([[1,2],[3,4]]).unsqueeze(-2) * torch.asarray([[5,6],[7,8]]).unsqueeze(-3)

tensor([[[ 5, 12],
         [ 7, 16]],

        [[15, 24],
         [21, 32]]])